[package]
name = "lib"
type = "bin"
authors = ["drone"]
compiler_version = ">=1.0.0"
version = "0.1.5"

[dependencies]
lib = { path = "../../../lib/noir-lib" }
hydra = { path = "../../../lib/noir-hydra" }
