[package]
name = "self_service"
type = "bin"
compiler_version = ">=0.30.0"

[build]
target-dir = "./target"

[dependencies]
ethereum = { path = "../../../ethereum/circuits/lib" }
token = { path = "../../../ethereum/circuits/lib" }
hydra = { path = "../../../lib/noir-hydra" }
keccak256 = { path = "../../../lib/keccak256" }